### ISSUE TITLE
请问如何自定义编辑器的placeholder？

### ISSUE THREAD

**Issue by hjplk** [capricorncd/zx-editor#28]

**Comment by capricorncd** [comment]
使用样式覆盖：scss
```scss
.zx-eidtor-container {
  .zxeditor-content-wrapper {
    &.is-empty &:before {
      content: '请输入正文内容' !important;
      color: #999 !important;
    }
  }
}
```
